namespace ProjectMannequin.Core;

public enum CombatPresentationEventType
{
    MoveStarted,
    DashStarted,
    JumpStarted,
    Landed,
    FlightStarted,
    FlightEnded,
    ParryStarted,
    HitConnected,
    Blocked,
    Parried,
    InstinctEvaded,
    CounterHit,
    PunishCounter,
    LauncherHit,
    ComboUpdated,
    GuardBroken,
    GuardRecovered,
    WallBounce,
    GroundBounce,
    SuperStarted,
    CinematicSuperStarted,
    FormSwapStarted,
    FormSwapCompleted,
    BossPhaseChanged,
    PlayerDowned,
    PlayerRevived,
    ActorDefeated,
    FormUnlocked,
    SynergyArtTriggered,
    FightRoomLocked,
    FightRoomOpened,
    WaveStarted,
    WaveCleared,
    WaveRewardGranted,
    PlayerCatchUpStarted,
    PlayerCatchUpCompleted,
    PlayerCatchUpWarped,
    EnemyEntryWarning,
    EnemyEntryCompleted,
    EncounterStarted,
    EnemyEntered,
    EncounterCleared,
    StageAdvanceOpened,
    HealthRestored,
    StageCompleted,
    HitStopStarted,
    BossIntroCutscene,
    BossIntroStarted,
    BossIntroReady,
    BossIntroFight,
    PlayerLifeLost,
    HazardZoneWarning,
    HazardZoneDamage,
    ArmorAbsorbed,
    AirRecovery,
    GameOver,
    AssistCallStarted,
    AssistCallCompleted,
    WallBreakStarted,
    BeamClashStarted,
    BeamClashUpdated,
    BeamClashResolved,
    ThrowTech,
    ReflectGuard,
    PhaseBurst,
    RushThrow,
    RewardOfferReady,
    RewardChosen,
    CorruptionDrain,
    EliteEnemySpawned,
    RouteChoiceReady,
    RouteChosen,
    StageIntroStarted,
    StageIntroReady,
    StageIntroFinished,
    ScoreChanged,
    StageResultsReady,
    ExtraLifeAwarded,
    EliteIntroStarted,
    EliteIntroReady,
    EliteIntroFight,
    PropExploded,
}

public readonly record struct CombatPresentationEvent(
    CombatPresentationEventType Type,
    int Tick,
    string SourceActorId,
    string TargetActorId = "",
    string Payload = "");
